### ISSUE TITLE
Update form not submitting

### ISSUE THREAD

**Issue by tacman** [tzunghaor/settings-bundle#3]
I think I'm following the instructions, but when I edit the settings, they're not being saved.

The issue is that $form->isSubmitted() is returning false, even though it looks like it's submitting correctly.

```yaml
# config/routes/tzunghaor_settings.yaml

settings_scope_search:
  path: '/settings/scope-search'
  controller: 'tzunghaor_settings.editor_controller::searchScope'

settings_edit:
  path: '/settings/edit/{scope?}/{section?}'
  controller: 'tzunghaor_settings.editor_controller::edit'
  defaults:
    collection: 'default'
    fixedParameters: ['collection']
    searchRoute: 'settings_scope_search'
```

I'm using the BoxSettings as described in the documentation.

```yaml
# config/packages/tzunghaor_settings.yaml
tzunghaor_settings:
  collections:
    # Each entry under "tzunghaor_settings" configures a setting collection.
    # Use "default" if you define only one collection
    default:
      mappings:
        # I used "default" as mapping name, but it is up to you.
        # You can have multiple mappings
        default:
          dir: '%kernel.project_dir%/src/Settings'
          prefix: App\Settings\
```

I imagine it's something simple, any ideas on where I should be looking?

**Comment by tacman** [comment]
I've created a repo that shows the problem:

https://github.com/tacman/settings-demo

**Comment by tzunghaor** [comment]
Thanks for the demo. 
In your framework.yaml set `http_method_override` to `true` and it should work.

Did you explicitly set that to false, or was it auto-generated? 

It seems that I should either update the documentation or check if using PATCH method for the form is worth the hassle.

**Comment by tacman** [comment]
That was auto-generated.

Thanks!

**Comment by jmwamser** [comment]
I ran into this issue as well. Looking into the Symfony community I found this. https://github.com/symfony/symfony/issues/45278 Sounds like this will be a default moving forward.

here is what my YAML file looks like now.

```
# config/packages/tzunghaor_settings.yaml
tzunghaor_settings:
  collections:
    # Each entry under "tzunghaor_settings" configures a setting collection.
    default:
      cache: 'cache.app'
      mappings:
        default:
          dir: '%kernel.project_dir%/src/Settings'
          prefix: App\Settings\

framework:
  # the form is not saving, due to default symfony configuration
  # https://github.com/tzunghaor/settings-bundle/issues/3
  # https://github.com/symfony/symfony/issues/45278
  http_method_override: true
```
